--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ahmed/Pictures/wallpapers/night-sky.png"

-- Special
background="#070C13"
foreground="#8fc8dc"
cursor="#8fc8dc"

-- Colors
color0="#070C13"
color1="#2F4B67"
color2="#504657"
color3="#92404B"
color4="#0D2C90"
color5="#116196"
color6="#494FB8"
color7="#8fc8dc"
color8="#648c9a"
color9="#2F4B67"
color10="#504657"
color11="#92404B"
color12="#0D2C90"
color13="#116196"
color14="#494FB8"
color15="#8fc8dc"
