# Shell variables
# Generated by 'wal'
wallpaper='/home/ahmed/Pictures/wallpapers/night-sky.png'

# Special
background='#070C13'
foreground='#8fc8dc'
cursor='#8fc8dc'

# Colors
color0='#070C13'
color1='#2F4B67'
color2='#504657'
color3='#92404B'
color4='#0D2C90'
color5='#116196'
color6='#494FB8'
color7='#8fc8dc'
color8='#648c9a'
color9='#2F4B67'
color10='#504657'
color11='#92404B'
color12='#0D2C90'
color13='#116196'
color14='#494FB8'
color15='#8fc8dc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
